/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package worldofpokimon;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.FlushModeType;
import javax.persistence.Persistence;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author ceess
 */
public class Main extends javax.swing.JFrame {
    Connection connection = null;
    Statement stmt = null;
    String yolo;
    String username;
    String password;
    String logInUsername;
    String logInPassword;
    String query;
    String loggedInUser;
    int radioText, monthsPayed, amountOfMoneyAdded, months_payed, balance;
    
    /*@PersistenceContext(unitName="WorldOfPokimonPU")
     private EntityManager em;
     public List<Users> getUsers() 
     {
     List<Users> users = em.createNamedQuery("findAll").getResultList();
     return users;
     }*/
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        try {
            connection = DriverManager.getConnection("jdbc:postgresql://localhost/dev1",
            "postgres", "lollipop");
            
        } catch ( Exception e ) {
         System.err.println( e.getClass().getName()+": "+ e.getMessage() );
         System.exit(0);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        mainScreen = new javax.swing.JPanel();
        registerScreenButton = new javax.swing.JButton();
        loginScreenButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        registerScreen = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        usernameText = new javax.swing.JLabel();
        usernameField = new javax.swing.JFormattedTextField();
        passwordText = new javax.swing.JLabel();
        firstNameText = new javax.swing.JLabel();
        firstNameField = new javax.swing.JFormattedTextField();
        lastNameText = new javax.swing.JLabel();
        lastNameField = new javax.swing.JFormattedTextField();
        IBANText = new javax.swing.JLabel();
        IBANField = new javax.swing.JFormattedTextField();
        passwordField = new javax.swing.JPasswordField();
        backButton = new javax.swing.JButton();
        loginScreen = new javax.swing.JPanel();
        logInButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        logInUsernameField = new javax.swing.JFormattedTextField();
        logInPasswordField = new javax.swing.JPasswordField();
        loginBackButton = new javax.swing.JButton();
        userScreen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        toCharacterButton = new javax.swing.JButton();
        toUserManButton = new javax.swing.JButton();
        characterManagementScreen = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        toNewCharButton = new javax.swing.JButton();
        charStatsButton = new javax.swing.JButton();
        toConnectServerButton = new javax.swing.JButton();
        charLogOut = new javax.swing.JButton();
        switchToUserButton = new javax.swing.JButton();
        userManagementScreen = new javax.swing.JPanel();
        toAddMoneyButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        toExtendSubButton = new javax.swing.JButton();
        toBuyCharsButton = new javax.swing.JButton();
        userLogOutButton = new javax.swing.JButton();
        switchToCharButton = new javax.swing.JButton();
        addMoneyScreen = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        addMoneyBackButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        moneyField = new javax.swing.JTextField();
        addMoneyButton = new javax.swing.JButton();
        extendSubscriptionScreen = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        esBackButton = new javax.swing.JButton();
        oneMonthSubscription = new javax.swing.JRadioButton();
        twoMonthsSubscription = new javax.swing.JRadioButton();
        threeMonthsSubscription = new javax.swing.JRadioButton();
        yearSubscription = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        confirmSubscriptionButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        subMoneyField = new javax.swing.JTextField();
        subBalance = new javax.swing.JLabel();
        buySlotsScreen = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        bsBackButton = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        amountOfSlotsField = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        addCharSlotsButton = new javax.swing.JButton();
        slotMoneyField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        createCharacterScreen = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        ccBackButton = new javax.swing.JButton();
        connectServerScreen = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        conServerBackButton = new javax.swing.JButton();
        charStatsScreen = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        csBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 0));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);

        mainPanel.setMaximumSize(new java.awt.Dimension(1000, 700));
        mainPanel.setLayout(new java.awt.CardLayout());

        mainScreen.setMaximumSize(new java.awt.Dimension(1000, 700));
        mainScreen.setMinimumSize(new java.awt.Dimension(1000, 700));
        mainScreen.setPreferredSize(new java.awt.Dimension(1000, 700));

        registerScreenButton.setText("Register");
        registerScreenButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        registerScreenButton.setMaximumSize(new java.awt.Dimension(180, 40));
        registerScreenButton.setMinimumSize(new java.awt.Dimension(180, 40));
        registerScreenButton.setPreferredSize(new java.awt.Dimension(180, 40));
        registerScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerScreenButtonActionPerformed(evt);
            }
        });

        loginScreenButton.setText("Log In");
        loginScreenButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginScreenButton.setMaximumSize(new java.awt.Dimension(180, 40));
        loginScreenButton.setMinimumSize(new java.awt.Dimension(180, 40));
        loginScreenButton.setPreferredSize(new java.awt.Dimension(180, 40));
        loginScreenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginScreenButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("World of Pokimon");

        javax.swing.GroupLayout mainScreenLayout = new javax.swing.GroupLayout(mainScreen);
        mainScreen.setLayout(mainScreenLayout);
        mainScreenLayout.setHorizontalGroup(
            mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainScreenLayout.createSequentialGroup()
                .addGroup(mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainScreenLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(loginScreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(registerScreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainScreenLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        mainScreenLayout.setVerticalGroup(
            mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainScreenLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginScreenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerScreenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(312, 312, 312))
        );

        mainPanel.add(mainScreen, "mainScreen");

        registerScreen.setMaximumSize(new java.awt.Dimension(1000, 700));
        registerScreen.setMinimumSize(new java.awt.Dimension(1000, 700));
        registerScreen.setPreferredSize(new java.awt.Dimension(1000, 700));

        registerButton.setText("Register");
        registerButton.setMaximumSize(new java.awt.Dimension(180, 40));
        registerButton.setMinimumSize(new java.awt.Dimension(180, 40));
        registerButton.setPreferredSize(new java.awt.Dimension(180, 40));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(130, 40));
        jLabel2.setMinimumSize(new java.awt.Dimension(130, 40));
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 40));

        usernameText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameText.setText("Username");
        usernameText.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });

        passwordText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordText.setText("Password");

        firstNameText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        firstNameText.setText("First Name");

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        lastNameText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lastNameText.setText("Last Name");

        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });

        IBANText.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        IBANText.setText("IBAN");

        IBANField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IBANFieldActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout registerScreenLayout = new javax.swing.GroupLayout(registerScreen);
        registerScreen.setLayout(registerScreenLayout);
        registerScreenLayout.setHorizontalGroup(
            registerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerScreenLayout.createSequentialGroup()
                .addGroup(registerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerScreenLayout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerScreenLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(backButton)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(registerScreenLayout.createSequentialGroup()
                .addGap(339, 339, 339)
                .addGroup(registerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(registerScreenLayout.createSequentialGroup()
                        .addComponent(IBANText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IBANField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerScreenLayout.createSequentialGroup()
                        .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerScreenLayout.createSequentialGroup()
                        .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerScreenLayout.createSequentialGroup()
                        .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerScreenLayout.createSequentialGroup()
                        .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(478, Short.MAX_VALUE))
        );
        registerScreenLayout.setVerticalGroup(
            registerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addGap(100, 100, 100)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(registerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(registerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameText))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(registerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IBANText)
                    .addComponent(IBANField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );

        mainPanel.add(registerScreen, "registerScreen");

        loginScreen.setMaximumSize(new java.awt.Dimension(1000, 700));
        loginScreen.setMinimumSize(new java.awt.Dimension(1000, 700));
        loginScreen.setPreferredSize(new java.awt.Dimension(1000, 700));

        logInButton.setText("Log In");
        logInButton.setMaximumSize(new java.awt.Dimension(180, 40));
        logInButton.setMinimumSize(new java.awt.Dimension(180, 40));
        logInButton.setPreferredSize(new java.awt.Dimension(180, 40));
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Log In");

        jLabel6.setText("Username");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Password");
        jLabel7.setMaximumSize(new java.awt.Dimension(48, 14));
        jLabel7.setMinimumSize(new java.awt.Dimension(48, 14));
        jLabel7.setPreferredSize(new java.awt.Dimension(48, 14));

        logInUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInUsernameFieldActionPerformed(evt);
            }
        });

        logInPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInPasswordFieldActionPerformed(evt);
            }
        });

        loginBackButton.setText("Back");
        loginBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginScreenLayout = new javax.swing.GroupLayout(loginScreen);
        loginScreen.setLayout(loginScreenLayout);
        loginScreenLayout.setHorizontalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginScreenLayout.createSequentialGroup()
                .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginScreenLayout.createSequentialGroup()
                        .addGap(389, 389, 389)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginScreenLayout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(loginScreenLayout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(logInPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(loginScreenLayout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(logInUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(451, Short.MAX_VALUE))
            .addGroup(loginScreenLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(loginBackButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        loginScreenLayout.setVerticalGroup(
            loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginScreenLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(loginBackButton)
                .addGap(68, 68, 68)
                .addComponent(jLabel4)
                .addGap(95, 95, 95)
                .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logInUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(38, 38, 38)
                .addGroup(loginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logInPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)
                .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        mainPanel.add(loginScreen, "loginScreen");

        userScreen.setMaximumSize(new java.awt.Dimension(1000, 700));
        userScreen.setMinimumSize(new java.awt.Dimension(1000, 700));
        userScreen.setPreferredSize(new java.awt.Dimension(1000, 700));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("User Screen");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(130, 30));
        jLabel1.setMinimumSize(new java.awt.Dimension(130, 30));
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 30));

        logOutButton.setText("Log Out");
        logOutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logOutButton.setMaximumSize(new java.awt.Dimension(180, 40));
        logOutButton.setMinimumSize(new java.awt.Dimension(180, 40));
        logOutButton.setPreferredSize(new java.awt.Dimension(180, 40));
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        toCharacterButton.setText("Go to Character Management");
        toCharacterButton.setMaximumSize(new java.awt.Dimension(180, 40));
        toCharacterButton.setPreferredSize(new java.awt.Dimension(180, 40));
        toCharacterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCharacterButtonActionPerformed(evt);
            }
        });

        toUserManButton.setText("Go to User Management");
        toUserManButton.setMaximumSize(new java.awt.Dimension(180, 40));
        toUserManButton.setMinimumSize(new java.awt.Dimension(180, 40));
        toUserManButton.setPreferredSize(new java.awt.Dimension(180, 40));
        toUserManButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toUserManButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userScreenLayout = new javax.swing.GroupLayout(userScreen);
        userScreen.setLayout(userScreenLayout);
        userScreenLayout.setHorizontalGroup(
            userScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userScreenLayout.createSequentialGroup()
                .addContainerGap(405, Short.MAX_VALUE)
                .addGroup(userScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toCharacterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toUserManButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(404, Short.MAX_VALUE))
        );
        userScreenLayout.setVerticalGroup(
            userScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userScreenLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166)
                .addComponent(toUserManButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128)
                .addComponent(toCharacterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        mainPanel.add(userScreen, "userScreen");

        characterManagementScreen.setMaximumSize(new java.awt.Dimension(1000, 700));
        characterManagementScreen.setMinimumSize(new java.awt.Dimension(1000, 700));
        characterManagementScreen.setPreferredSize(new java.awt.Dimension(1000, 700));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Character Management");

        toNewCharButton.setText("Create New Character");
        toNewCharButton.setMaximumSize(new java.awt.Dimension(180, 40));
        toNewCharButton.setMinimumSize(new java.awt.Dimension(180, 40));
        toNewCharButton.setPreferredSize(new java.awt.Dimension(180, 40));
        toNewCharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toNewCharButtonActionPerformed(evt);
            }
        });

        charStatsButton.setText("Character Statistics");
        charStatsButton.setMaximumSize(new java.awt.Dimension(180, 40));
        charStatsButton.setMinimumSize(new java.awt.Dimension(180, 40));
        charStatsButton.setPreferredSize(new java.awt.Dimension(180, 40));
        charStatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charStatsButtonActionPerformed(evt);
            }
        });

        toConnectServerButton.setText("Connect to Server");
        toConnectServerButton.setMaximumSize(new java.awt.Dimension(180, 40));
        toConnectServerButton.setMinimumSize(new java.awt.Dimension(180, 40));
        toConnectServerButton.setPreferredSize(new java.awt.Dimension(180, 40));
        toConnectServerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toConnectServerButtonActionPerformed(evt);
            }
        });

        charLogOut.setText("Log Out");
        charLogOut.setMaximumSize(new java.awt.Dimension(180, 40));
        charLogOut.setMinimumSize(new java.awt.Dimension(180, 40));
        charLogOut.setPreferredSize(new java.awt.Dimension(180, 40));
        charLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charLogOutActionPerformed(evt);
            }
        });

        switchToUserButton.setText("Switch to User");
        switchToUserButton.setMaximumSize(new java.awt.Dimension(180, 40));
        switchToUserButton.setMinimumSize(new java.awt.Dimension(180, 40));
        switchToUserButton.setPreferredSize(new java.awt.Dimension(180, 40));
        switchToUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchToUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout characterManagementScreenLayout = new javax.swing.GroupLayout(characterManagementScreen);
        characterManagementScreen.setLayout(characterManagementScreenLayout);
        characterManagementScreenLayout.setHorizontalGroup(
            characterManagementScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(characterManagementScreenLayout.createSequentialGroup()
                .addGroup(characterManagementScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(characterManagementScreenLayout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel8))
                    .addGroup(characterManagementScreenLayout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addGroup(characterManagementScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(charStatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toNewCharButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toConnectServerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(switchToUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(charLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        characterManagementScreenLayout.setVerticalGroup(
            characterManagementScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(characterManagementScreenLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel8)
                .addGap(56, 56, 56)
                .addComponent(toNewCharButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(charStatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(toConnectServerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(switchToUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(charLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        mainPanel.add(characterManagementScreen, "characterManagementScreen");

        userManagementScreen.setMaximumSize(new java.awt.Dimension(1000, 700));
        userManagementScreen.setMinimumSize(new java.awt.Dimension(1000, 700));
        userManagementScreen.setPreferredSize(new java.awt.Dimension(1000, 700));

        toAddMoneyButton.setText("Add Money to Account");
        toAddMoneyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toAddMoneyButton.setMaximumSize(new java.awt.Dimension(180, 40));
        toAddMoneyButton.setMinimumSize(new java.awt.Dimension(180, 40));
        toAddMoneyButton.setPreferredSize(new java.awt.Dimension(180, 40));
        toAddMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toAddMoneyButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setText("User Management");

        toExtendSubButton.setText("Extend Subscription");
        toExtendSubButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toExtendSubButton.setMaximumSize(new java.awt.Dimension(180, 40));
        toExtendSubButton.setMinimumSize(new java.awt.Dimension(180, 40));
        toExtendSubButton.setPreferredSize(new java.awt.Dimension(180, 40));
        toExtendSubButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toExtendSubButtonActionPerformed(evt);
            }
        });

        toBuyCharsButton.setText("Buy Character Slots");
        toBuyCharsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toBuyCharsButton.setMaximumSize(new java.awt.Dimension(180, 40));
        toBuyCharsButton.setMinimumSize(new java.awt.Dimension(180, 40));
        toBuyCharsButton.setPreferredSize(new java.awt.Dimension(180, 40));
        toBuyCharsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toBuyCharsButtonActionPerformed(evt);
            }
        });

        userLogOutButton.setText("Log Out");
        userLogOutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userLogOutButton.setMaximumSize(new java.awt.Dimension(180, 40));
        userLogOutButton.setMinimumSize(new java.awt.Dimension(180, 40));
        userLogOutButton.setPreferredSize(new java.awt.Dimension(180, 40));
        userLogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLogOutButtonActionPerformed(evt);
            }
        });

        switchToCharButton.setText("Switch to Character");
        switchToCharButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        switchToCharButton.setMaximumSize(new java.awt.Dimension(180, 40));
        switchToCharButton.setMinimumSize(new java.awt.Dimension(180, 40));
        switchToCharButton.setPreferredSize(new java.awt.Dimension(180, 40));
        switchToCharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchToCharButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userManagementScreenLayout = new javax.swing.GroupLayout(userManagementScreen);
        userManagementScreen.setLayout(userManagementScreenLayout);
        userManagementScreenLayout.setHorizontalGroup(
            userManagementScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userManagementScreenLayout.createSequentialGroup()
                .addContainerGap(330, Short.MAX_VALUE)
                .addGroup(userManagementScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(userManagementScreenLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(381, 381, 381))
                    .addGroup(userManagementScreenLayout.createSequentialGroup()
                        .addGroup(userManagementScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(toExtendSubButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toAddMoneyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toBuyCharsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(switchToCharButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userLogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(433, 433, 433))))
        );
        userManagementScreenLayout.setVerticalGroup(
            userManagementScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userManagementScreenLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel5)
                .addGap(71, 71, 71)
                .addComponent(toAddMoneyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toExtendSubButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(toBuyCharsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(switchToCharButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(userLogOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        mainPanel.add(userManagementScreen, "userManagementScreen");

        addMoneyScreen.setMaximumSize(new java.awt.Dimension(1000, 700));
        addMoneyScreen.setMinimumSize(new java.awt.Dimension(1000, 700));
        addMoneyScreen.setPreferredSize(new java.awt.Dimension(1000, 700));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setText("User Management");

        addMoneyBackButton.setText("Back");
        addMoneyBackButton.setMaximumSize(new java.awt.Dimension(180, 40));
        addMoneyBackButton.setMinimumSize(new java.awt.Dimension(180, 40));
        addMoneyBackButton.setPreferredSize(new java.awt.Dimension(180, 40));
        addMoneyBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoneyBackButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("Amount of Money");

        addMoneyButton.setText("Add Money to Account");
        addMoneyButton.setMaximumSize(new java.awt.Dimension(180, 40));
        addMoneyButton.setMinimumSize(new java.awt.Dimension(180, 40));
        addMoneyButton.setPreferredSize(new java.awt.Dimension(180, 40));
        addMoneyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMoneyButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addMoneyScreenLayout = new javax.swing.GroupLayout(addMoneyScreen);
        addMoneyScreen.setLayout(addMoneyScreenLayout);
        addMoneyScreenLayout.setHorizontalGroup(
            addMoneyScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMoneyScreenLayout.createSequentialGroup()
                .addGroup(addMoneyScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addMoneyScreenLayout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(jLabel12))
                    .addGroup(addMoneyScreenLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addGroup(addMoneyScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addMoneyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addMoneyScreenLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(moneyField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(addMoneyScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addMoneyBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(400, Short.MAX_VALUE))
        );
        addMoneyScreenLayout.setVerticalGroup(
            addMoneyScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addMoneyScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addMoneyBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel12)
                .addGap(101, 101, 101)
                .addGroup(addMoneyScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(moneyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(76, 76, 76)
                .addComponent(addMoneyButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(326, Short.MAX_VALUE))
        );

        mainPanel.add(addMoneyScreen, "addMoneyScreen");

        extendSubscriptionScreen.setMaximumSize(new java.awt.Dimension(1000, 700));
        extendSubscriptionScreen.setMinimumSize(new java.awt.Dimension(1000, 700));
        extendSubscriptionScreen.setPreferredSize(new java.awt.Dimension(1000, 700));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel13.setText("User Management");

        esBackButton.setText("Back");
        esBackButton.setMaximumSize(new java.awt.Dimension(180, 40));
        esBackButton.setMinimumSize(new java.awt.Dimension(180, 40));
        esBackButton.setPreferredSize(new java.awt.Dimension(180, 40));
        esBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esBackButtonActionPerformed(evt);
            }
        });

        oneMonthSubscription.setText("5");

        twoMonthsSubscription.setText("8");

        threeMonthsSubscription.setText("10");

        yearSubscription.setText("35");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Subscription");

        confirmSubscriptionButton.setText("Confirm Subscription");
        confirmSubscriptionButton.setMaximumSize(new java.awt.Dimension(180, 40));
        confirmSubscriptionButton.setMinimumSize(new java.awt.Dimension(180, 40));
        confirmSubscriptionButton.setPreferredSize(new java.awt.Dimension(180, 40));
        confirmSubscriptionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmSubscriptionButtonActionPerformed(evt);
            }
        });

        jLabel17.setText("€ - One Month");

        jLabel18.setText("€ - Two Months");

        jLabel19.setText("€ - Three Months");

        jLabel20.setText("€ - Year");

        subMoneyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subMoneyFieldActionPerformed(evt);
            }
        });

        subBalance.setText("Balance :");

        javax.swing.GroupLayout extendSubscriptionScreenLayout = new javax.swing.GroupLayout(extendSubscriptionScreen);
        extendSubscriptionScreen.setLayout(extendSubscriptionScreenLayout);
        extendSubscriptionScreenLayout.setHorizontalGroup(
            extendSubscriptionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extendSubscriptionScreenLayout.createSequentialGroup()
                .addGroup(extendSubscriptionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(extendSubscriptionScreenLayout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addGroup(extendSubscriptionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(extendSubscriptionScreenLayout.createSequentialGroup()
                                .addComponent(oneMonthSubscription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17))
                            .addGroup(extendSubscriptionScreenLayout.createSequentialGroup()
                                .addComponent(threeMonthsSubscription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19))
                            .addComponent(jLabel16)
                            .addGroup(extendSubscriptionScreenLayout.createSequentialGroup()
                                .addComponent(twoMonthsSubscription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18))))
                    .addGroup(extendSubscriptionScreenLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel13))
                    .addGroup(extendSubscriptionScreenLayout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(yearSubscription)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20))
                    .addGroup(extendSubscriptionScreenLayout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(confirmSubscriptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(extendSubscriptionScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(esBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(377, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, extendSubscriptionScreenLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(subBalance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subMoneyField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        extendSubscriptionScreenLayout.setVerticalGroup(
            extendSubscriptionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(extendSubscriptionScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(esBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(extendSubscriptionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subMoneyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subBalance))
                .addGap(31, 31, 31)
                .addComponent(jLabel13)
                .addGap(33, 33, 33)
                .addComponent(jLabel16)
                .addGap(27, 27, 27)
                .addGroup(extendSubscriptionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(oneMonthSubscription))
                .addGap(18, 18, 18)
                .addGroup(extendSubscriptionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(twoMonthsSubscription)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(extendSubscriptionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(threeMonthsSubscription)
                    .addComponent(jLabel19))
                .addGap(9, 9, 9)
                .addGroup(extendSubscriptionScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearSubscription)
                    .addComponent(jLabel20))
                .addGap(79, 79, 79)
                .addComponent(confirmSubscriptionButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        mainPanel.add(extendSubscriptionScreen, "extendSubscriptionScreen");

        buySlotsScreen.setMaximumSize(new java.awt.Dimension(1000, 700));
        buySlotsScreen.setMinimumSize(new java.awt.Dimension(1000, 700));
        buySlotsScreen.setPreferredSize(new java.awt.Dimension(1000, 700));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel14.setText("User Management");

        bsBackButton.setText("Back");
        bsBackButton.setMaximumSize(new java.awt.Dimension(180, 40));
        bsBackButton.setMinimumSize(new java.awt.Dimension(180, 40));
        bsBackButton.setPreferredSize(new java.awt.Dimension(180, 40));
        bsBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsBackButtonActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("How many slots do you want to buy?");

        jLabel22.setText("Slots");

        jLabel23.setText("€1 per character slot");

        addCharSlotsButton.setText("Buy Slot(s)");
        addCharSlotsButton.setMaximumSize(new java.awt.Dimension(180, 40));
        addCharSlotsButton.setMinimumSize(new java.awt.Dimension(180, 40));
        addCharSlotsButton.setPreferredSize(new java.awt.Dimension(180, 40));
        addCharSlotsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCharSlotsButtonActionPerformed(evt);
            }
        });

        jLabel24.setText("Balance :");

        javax.swing.GroupLayout buySlotsScreenLayout = new javax.swing.GroupLayout(buySlotsScreen);
        buySlotsScreen.setLayout(buySlotsScreenLayout);
        buySlotsScreenLayout.setHorizontalGroup(
            buySlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buySlotsScreenLayout.createSequentialGroup()
                .addGroup(buySlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buySlotsScreenLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(jLabel14))
                    .addGroup(buySlotsScreenLayout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addGroup(buySlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buySlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addCharSlotsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(buySlotsScreenLayout.createSequentialGroup()
                                    .addComponent(amountOfSlotsField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(buySlotsScreenLayout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel23)))
                .addContainerGap(402, Short.MAX_VALUE))
            .addGroup(buySlotsScreenLayout.createSequentialGroup()
                .addGroup(buySlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buySlotsScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(buySlotsScreenLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)))
                .addComponent(slotMoneyField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        buySlotsScreenLayout.setVerticalGroup(
            buySlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buySlotsScreenLayout.createSequentialGroup()
                .addGroup(buySlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buySlotsScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(bsBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buySlotsScreenLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(buySlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(slotMoneyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))))
                .addGap(31, 31, 31)
                .addComponent(jLabel14)
                .addGap(82, 82, 82)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addGap(45, 45, 45)
                .addGroup(buySlotsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(amountOfSlotsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(78, 78, 78)
                .addComponent(addCharSlotsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        mainPanel.add(buySlotsScreen, "buySlotsScreen");

        createCharacterScreen.setMaximumSize(new java.awt.Dimension(1000, 700));
        createCharacterScreen.setMinimumSize(new java.awt.Dimension(1000, 700));
        createCharacterScreen.setPreferredSize(new java.awt.Dimension(1000, 700));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel9.setText("Character Management");

        ccBackButton.setText("Back");
        ccBackButton.setMaximumSize(new java.awt.Dimension(180, 40));
        ccBackButton.setMinimumSize(new java.awt.Dimension(180, 40));
        ccBackButton.setPreferredSize(new java.awt.Dimension(180, 40));
        ccBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout createCharacterScreenLayout = new javax.swing.GroupLayout(createCharacterScreen);
        createCharacterScreen.setLayout(createCharacterScreenLayout);
        createCharacterScreenLayout.setHorizontalGroup(
            createCharacterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCharacterScreenLayout.createSequentialGroup()
                .addGroup(createCharacterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(createCharacterScreenLayout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jLabel9))
                    .addGroup(createCharacterScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ccBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(341, Short.MAX_VALUE))
        );
        createCharacterScreenLayout.setVerticalGroup(
            createCharacterScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(createCharacterScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ccBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel9)
                .addContainerGap(580, Short.MAX_VALUE))
        );

        mainPanel.add(createCharacterScreen, "createCharacterScreen");

        connectServerScreen.setMaximumSize(new java.awt.Dimension(1000, 700));
        connectServerScreen.setMinimumSize(new java.awt.Dimension(1000, 700));
        connectServerScreen.setPreferredSize(new java.awt.Dimension(1000, 700));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("Character Management");
        jLabel11.setInheritsPopupMenu(false);

        conServerBackButton.setText("Back");
        conServerBackButton.setMaximumSize(new java.awt.Dimension(180, 40));
        conServerBackButton.setMinimumSize(new java.awt.Dimension(180, 40));
        conServerBackButton.setPreferredSize(new java.awt.Dimension(180, 40));
        conServerBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conServerBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout connectServerScreenLayout = new javax.swing.GroupLayout(connectServerScreen);
        connectServerScreen.setLayout(connectServerScreenLayout);
        connectServerScreenLayout.setHorizontalGroup(
            connectServerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectServerScreenLayout.createSequentialGroup()
                .addGroup(connectServerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(connectServerScreenLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabel11))
                    .addGroup(connectServerScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(conServerBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        connectServerScreenLayout.setVerticalGroup(
            connectServerScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(connectServerScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(conServerBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel11)
                .addContainerGap(577, Short.MAX_VALUE))
        );

        mainPanel.add(connectServerScreen, "connectServerScreen");

        charStatsScreen.setMaximumSize(new java.awt.Dimension(1000, 700));
        charStatsScreen.setMinimumSize(new java.awt.Dimension(1000, 700));
        charStatsScreen.setPreferredSize(new java.awt.Dimension(1000, 700));
        charStatsScreen.setRequestFocusEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("Character Management");

        csBackButton.setText("Back");
        csBackButton.setMaximumSize(new java.awt.Dimension(180, 40));
        csBackButton.setMinimumSize(new java.awt.Dimension(180, 40));
        csBackButton.setPreferredSize(new java.awt.Dimension(180, 40));
        csBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout charStatsScreenLayout = new javax.swing.GroupLayout(charStatsScreen);
        charStatsScreen.setLayout(charStatsScreenLayout);
        charStatsScreenLayout.setHorizontalGroup(
            charStatsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(charStatsScreenLayout.createSequentialGroup()
                .addGroup(charStatsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(charStatsScreenLayout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel10))
                    .addGroup(charStatsScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(csBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(343, Short.MAX_VALUE))
        );
        charStatsScreenLayout.setVerticalGroup(
            charStatsScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(charStatsScreenLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(csBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(605, Short.MAX_VALUE))
        );

        mainPanel.add(charStatsScreen, "charStatsScreen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginScreenButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "loginScreen");
    }//GEN-LAST:event_loginScreenButtonActionPerformed

    private void registerScreenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerScreenButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "registerScreen");
    }//GEN-LAST:event_registerScreenButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        getRegistration();
    }//GEN-LAST:event_registerButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "mainScreen");
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        getUser();
    }//GEN-LAST:event_logInButtonActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void IBANFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IBANFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IBANFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void logInUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logInUsernameFieldActionPerformed

    private void logInPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logInPasswordFieldActionPerformed

    private void toCharacterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toCharacterButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "characterManagementScreen");
    }//GEN-LAST:event_toCharacterButtonActionPerformed

    private void toUserManButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toUserManButtonActionPerformed
        System.out.println("does this work");
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "userManagementScreen");
    }//GEN-LAST:event_toUserManButtonActionPerformed

    private void switchToCharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchToCharButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "characterManagementScreen");
    }//GEN-LAST:event_switchToCharButtonActionPerformed

    private void userLogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLogOutButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "mainScreen");
    }//GEN-LAST:event_userLogOutButtonActionPerformed

    private void switchToUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchToUserButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "userManagementScreen");
    }//GEN-LAST:event_switchToUserButtonActionPerformed

    private void charLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charLogOutActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "mainScreen");
    }//GEN-LAST:event_charLogOutActionPerformed

    private void toAddMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toAddMoneyButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "addMoneyScreen");
    }//GEN-LAST:event_toAddMoneyButtonActionPerformed

    private void toExtendSubButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toExtendSubButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "extendSubscriptionScreen");
        groupButton();
        getBalance();
        subMoneyField.setText(Integer.toString(balance));
    }//GEN-LAST:event_toExtendSubButtonActionPerformed

    private void toBuyCharsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toBuyCharsButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "buySlotsScreen");
        getBalance();
        slotMoneyField.setText(Integer.toString(balance));
    }//GEN-LAST:event_toBuyCharsButtonActionPerformed

    private void toNewCharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toNewCharButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "createCharacterScreen");
    }//GEN-LAST:event_toNewCharButtonActionPerformed

    private void toConnectServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toConnectServerButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "connectServerScreen");//jj
    }//GEN-LAST:event_toConnectServerButtonActionPerformed

    private void charStatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charStatsButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "charStatsScreen");
    }//GEN-LAST:event_charStatsButtonActionPerformed

    private void addMoneyBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoneyBackButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "userManagementScreen");
    }//GEN-LAST:event_addMoneyBackButtonActionPerformed

    private void esBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esBackButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "userManagementScreen");
    }//GEN-LAST:event_esBackButtonActionPerformed

    private void bsBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsBackButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "userManagementScreen");
    }//GEN-LAST:event_bsBackButtonActionPerformed

    private void ccBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccBackButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "characterManagementScreen");
    }//GEN-LAST:event_ccBackButtonActionPerformed

    private void conServerBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conServerBackButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "characterManagementScreen");
    }//GEN-LAST:event_conServerBackButtonActionPerformed

    private void csBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csBackButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "characterManagementScreen");
    }//GEN-LAST:event_csBackButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "mainScreen");
        emtpyFields();
    }//GEN-LAST:event_backButtonActionPerformed

    private void loginBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBackButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "mainScreen");
    }//GEN-LAST:event_loginBackButtonActionPerformed

    private void addMoneyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMoneyButtonActionPerformed
        addMoney();
        //executeBalanceUpdate();
        JOptionPane.showMessageDialog(addMoneyScreen, "You have added €"+amountOfMoneyAdded+" to your account");
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "userManagementScreen");
        moneyField.setText("");
    }//GEN-LAST:event_addMoneyButtonActionPerformed

    private void confirmSubscriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmSubscriptionButtonActionPerformed
        checkBalance();
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "userManagementScreen");
    }//GEN-LAST:event_confirmSubscriptionButtonActionPerformed

    private void addCharSlotsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCharSlotsButtonActionPerformed
        addSlots();
        amountOfSlotsField.setText("");
    }//GEN-LAST:event_addCharSlotsButtonActionPerformed

    private void subMoneyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subMoneyFieldActionPerformed

    }//GEN-LAST:event_subMoneyFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    public void getRegistration()
    {
        
        String reg_username = usernameField.getText();
        String reg_password = passwordField.getText();
        String reg_firstName = firstNameField.getText();      
        String reg_lastName = lastNameField.getText();
        String reg_iban = IBANField.getText();
        try {
            stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery( "SELECT * FROM Users WHERE user_name = '" + reg_username + "';" );
            while ( rs.next() ) {
                username = rs.getString("user_name");
                password  = rs.getString("password");
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(reg_username.equals(username)){
            JOptionPane.showMessageDialog(registerScreen, "Username already in use.");
            usernameField.setText("");
        } else{
            Users s = new Users();
            System.out.println(reg_username);
            s.setUserName(reg_username);
            s.setPassword(reg_password);
            s.setFirstName(reg_firstName);
            s.setLastName(reg_lastName);
            s.setIban(reg_iban);
            persist(s);
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "mainScreen");
            emtpyFields();
        }
        
        
    }
    
    public void emtpyFields()
    {
            usernameField.setText("");
            passwordField.setText("");
            IBANField.setText("");
            firstNameField.setText("");
            lastNameField.setText("");
    }
    
    public void getUser(){
        logInUsername = logInUsernameField.getText();
        logInPassword = logInPasswordField.getText();
        loggedInUser = logInUsernameField.getText();
        
        try {
            stmt = connection.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM users WHERE user_name = '" + 
                    logInUsername + "' AND password = '" + logInPassword + "'");
            if(rs.next()){
                
                CardLayout card = (CardLayout)mainPanel.getLayout();
                card.show(mainPanel, "userScreen");
            
            }else{
                
                JOptionPane.showMessageDialog(loginScreen, "Incorrect Username and/or password");
            
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void addMoney()
    {
        amountOfMoneyAdded = Integer.parseInt(moneyField.getText());
        
        try
        {
            stmt = connection.createStatement();
            
            String updateBalance = "UPDATE Users SET balance = balance + '"+amountOfMoneyAdded+"' " 
                    + "WHERE user_name = '"+loggedInUser+"'";
            stmt.executeUpdate(updateBalance);
            
        } catch (Exception e)
        {
          e.getMessage();
        }
    }
    
    /*public void executeBalanceUpdate()
    {
        //int balance, String user_name
        //int amountOfMoneyAdded = Integer.parseInt(moneyField.getText());
        
          Query update_query = em.createNamedQuery("updateBalance");
          //update_query.setParameter(1, amountOfMoneyAdded);
          update_query.setParameter(1, loggedInUser);
          int updateData = update_query.executeUpdate();
          System.out.print(updateData);
          //em.setFlushMode(FlushModeType.COMMIT);
          //em.close();
          //return updateData;
          
     }*/
    
    private void groupButton()
    {
        ButtonGroup bgSubscription = new ButtonGroup();
        
        bgSubscription.add(oneMonthSubscription);
        bgSubscription.add(twoMonthsSubscription);
        bgSubscription.add(threeMonthsSubscription);
        bgSubscription.add(yearSubscription);
    }
    
    public void radioText()
    {          
        if (oneMonthSubscription.isSelected())
        {
            radioText = Integer.parseInt(oneMonthSubscription.getText());
            monthsPayed = 1;
            System.out.println(radioText);        
        } else if (twoMonthsSubscription.isSelected())
        {
            radioText = Integer.parseInt(twoMonthsSubscription.getText());
            monthsPayed = 2;
            System.out.println(radioText);        
        } else if (threeMonthsSubscription.isSelected())
        {
            radioText = Integer.parseInt(threeMonthsSubscription.getText());
            monthsPayed = 3;
            System.out.println(radioText);                 
        } else if (yearSubscription.isSelected()) 
        {
            radioText = Integer.parseInt(yearSubscription.getText());
            monthsPayed = 12;
            System.out.println(radioText);         
        }
    }
        public void subscribe(){
          
        try
        {
            stmt = connection.createStatement();
            
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
	    //get current date time with Date()
	    Date date = new Date();
            System.out.println(dateFormat.format(date));
            String characterQuery = "Update Users Set character_slots = 5 WHERE user_name = '" +loggedInUser+"'";
            String characterQuery2 = "SELECT character_slots FROM Users WHERE user_name= '" +loggedInUser+"'";
            ResultSet rs = stmt.executeQuery(characterQuery2);
            while(rs.next()){
            
                if(rs.getInt("character_slots") == 0){
                
                    stmt.executeQuery(characterQuery);
                }
            }
            
            
            String subscriptionQuery = "UPDATE Users SET balance = balance - '"+radioText+"', last_payment = '"+dateFormat.format(date)+"' "
                    + ",months_payed = months_payed + '"+monthsPayed+"' WHERE user_name = '"+loggedInUser+"'";
            stmt.executeUpdate(subscriptionQuery);
            
            
        } catch (Exception e)
        {
          e.getMessage();
        }
        JOptionPane.showMessageDialog(addMoneyScreen, "Thank you for subscribing!");
    }
    
    public void checkBalance(){
        radioText();
    
        try {
            stmt = connection.createStatement();
            String query = "Select balance FROM users WHERE user_name = '" + loggedInUser +"'";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
            System.out.println(radioText);
            balance = rs.getInt("balance");
            if(balance >= radioText){
                subscribe();
                System.out.println("balance = " + balance);
            } else{
                JOptionPane.showMessageDialog(extendSubscriptionScreen, "not enough balance");
            }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void addSlots()
    {
        int amountOfSlots = Integer.parseInt(amountOfSlotsField.getText());
        int moneyForSlots = amountOfSlots * 1 ;

        try
        {
            stmt = connection.createStatement();
            String slotsQuery = "SELECT balance, months_payed FROM users WHERE user_name = '" + loggedInUser +"'";
            ResultSet rs = stmt.executeQuery(slotsQuery);
            while(rs.next()){
                int userBalance = rs.getInt("balance");
                int months_payedd = rs.getInt("months_payed");
                System.out.println("balance: " + userBalance + ", months_payed: " + months_payedd);
                    
                if (userBalance > moneyForSlots && months_payedd > 0)
                {
                    String subscriptionQuery = "UPDATE Users SET character_slots = character_slots + '"+amountOfSlots+"'," 
                        + "balance = balance - '"+moneyForSlots+"' WHERE user_name = '"+loggedInUser+"' AND months_payed IS NOT NULL";
                    stmt.executeUpdate(subscriptionQuery);
                    JOptionPane.showMessageDialog(buySlotsScreen, "You've bought "+amountOfSlots+" slots");
                    CardLayout card = (CardLayout)mainPanel.getLayout();
                    card.show(mainPanel, "userManagementScreen");
                } else
                {
                    JOptionPane.showMessageDialog(buySlotsScreen, "Your don't have enough balance to buy a slot, or you don't have a subscription");
                }
            }
            
            
        } catch (Exception e)
        {
          e.getMessage();
        }
    }    
    
    public static void persist(Object object) 
    {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("WorldOfPokimonPU");
        EntityManager em = emf.createEntityManager();
        em.getTransaction().begin();
        try {
            em.persist(object);
            em.getTransaction().commit();
        } catch (Exception e) {
            e.printStackTrace();
            em.getTransaction().rollback();
        } finally {
            em.close();
        }
        
    }
    public void getBalance(){
        
        try {
            String query = "Select balance FROM users WHERE user_name = '" + loggedInUser +"'";
            ResultSet rs;
            rs = stmt.executeQuery(query);
            stmt = connection.createStatement();
            while(rs.next()){
            balance = rs.getInt("balance");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField IBANField;
    private javax.swing.JLabel IBANText;
    private javax.swing.JButton addCharSlotsButton;
    private javax.swing.JButton addMoneyBackButton;
    private javax.swing.JButton addMoneyButton;
    private javax.swing.JPanel addMoneyScreen;
    private javax.swing.JTextField amountOfSlotsField;
    private javax.swing.JButton backButton;
    private javax.swing.JButton bsBackButton;
    private javax.swing.JPanel buySlotsScreen;
    private javax.swing.JButton ccBackButton;
    private javax.swing.JButton charLogOut;
    private javax.swing.JButton charStatsButton;
    private javax.swing.JPanel charStatsScreen;
    private javax.swing.JPanel characterManagementScreen;
    private javax.swing.JButton conServerBackButton;
    private javax.swing.JButton confirmSubscriptionButton;
    private javax.swing.JPanel connectServerScreen;
    private javax.swing.JPanel createCharacterScreen;
    private javax.swing.JButton csBackButton;
    private javax.swing.JButton esBackButton;
    private javax.swing.JPanel extendSubscriptionScreen;
    private javax.swing.JFormattedTextField firstNameField;
    private javax.swing.JLabel firstNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField lastNameField;
    private javax.swing.JLabel lastNameText;
    private javax.swing.JButton logInButton;
    private javax.swing.JPasswordField logInPasswordField;
    private javax.swing.JFormattedTextField logInUsernameField;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton loginBackButton;
    private javax.swing.JPanel loginScreen;
    private javax.swing.JButton loginScreenButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mainScreen;
    private javax.swing.JTextField moneyField;
    private javax.swing.JRadioButton oneMonthSubscription;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordText;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel registerScreen;
    private javax.swing.JButton registerScreenButton;
    private javax.swing.JTextField slotMoneyField;
    private javax.swing.JLabel subBalance;
    private javax.swing.JTextField subMoneyField;
    private javax.swing.JButton switchToCharButton;
    private javax.swing.JButton switchToUserButton;
    private javax.swing.JRadioButton threeMonthsSubscription;
    private javax.swing.JButton toAddMoneyButton;
    private javax.swing.JButton toBuyCharsButton;
    private javax.swing.JButton toCharacterButton;
    private javax.swing.JButton toConnectServerButton;
    private javax.swing.JButton toExtendSubButton;
    private javax.swing.JButton toNewCharButton;
    private javax.swing.JButton toUserManButton;
    private javax.swing.JRadioButton twoMonthsSubscription;
    private javax.swing.JButton userLogOutButton;
    private javax.swing.JPanel userManagementScreen;
    private javax.swing.JPanel userScreen;
    private javax.swing.JFormattedTextField usernameField;
    private javax.swing.JLabel usernameText;
    private javax.swing.JRadioButton yearSubscription;
    // End of variables declaration//GEN-END:variables

}
